DEFAULT_ROLES = {
    "SUPER_ADMIN": {
        "name": "SUPER_ADMIN",
        "description": "Full system access",
        "is_immutable": True,
        "permissions": [
            "branches:create",
            "branches:read",
            "branches:update",
            "branches:delete",
            "buy_invoices:create",
            "buy_invoices:read",
            "buy_invoices:update",
            "buy_invoices:delete",
            "customers:create",
            "customers:read",
            "customers:update",
            "customers:delete",
            "invoices:create",
            "invoices:read",
            "invoices:update",
            "invoices:delete",
            "items:create",
            "items:read",
            "items:update",
            "items:delete",
            "organizations:create",
            "organizations:read",
            "organizations:update",
            "organizations:delete",
            "points_of_sale:create",
            "points_of_sale:read",
            "points_of_sale:update",
            "points_of_sale:delete",
            "projects:create",
            "projects:read",
            "projects:update",
            "projects:delete",
            "sale_invoices:create",
            "sale_invoices:read",
            "sale_invoices:update",
            "sale_invoices:delete",
            "suppliers:create",
            "suppliers:read",
            "suppliers:update",
            "suppliers:delete",
            "users:create",
            "users:read",
            "users:update",
            "users:delete"
        ],
    },
    "USER": {
        "name": "USER",
        "description": "Standard user role with limited permissions.",
        "is_immutable": False,
        "permissions": [
            "branches:create",
            "branches:read",
            "branches:update",
            "branches:delete",
            "buy_invoices:create",
            "buy_invoices:read",
            "buy_invoices:update",
            "buy_invoices:delete",
            "customers:create",
            "customers:read",
            "customers:update",
            "customers:delete",
            "invoices:create",
            "invoices:read",
            "invoices:update",
            "invoices:delete",
            "items:create",
            "items:read",
            "items:update",
            "items:delete",
            "organizations:create",
            "organizations:read",
            "organizations:update",
            "organizations:delete",
            "points_of_sale:create",
            "points_of_sale:read",
            "points_of_sale:update",
            "points_of_sale:delete",
            "projects:create",
            "projects:read",
            "projects:update",
            "projects:delete",
            "sale_invoices:create",
            "sale_invoices:read",
            "sale_invoices:update",
            "sale_invoices:delete",
            "suppliers:create",
            "suppliers:read",
            "suppliers:update",
            "suppliers:delete",
            "users:create",
            "users:read",
            "users:update",
            "users:delete"
        ],
    },
}