"""updated invoice customer

Revision ID: 00613cc2d289
Revises: d1627b8add9a
Create Date: 2025-08-27 20:58:21.011927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00613cc2d289'
down_revision: Union[str, None] = 'd1627b8add9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('registration_name', sa.String(length=250), nullable=False),
    sa.Column('vat_number', sa.String(length=20), nullable=True),
    sa.Column('country_code', sa.String(length=5), server_default='SA', nullable=True),
    sa.Column('street', sa.String(length=300), nullable=True),
    sa.Column('building_number', sa.String(length=15), nullable=True),
    sa.Column('division', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('party_identification_scheme', sa.String(length=10), nullable=False),
    sa.Column('party_identification_value', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_snapshots_id'), 'customer_snapshots', ['id'], unique=False)
    op.drop_index('ix_invoices_customers_id', table_name='invoices_customers')
    op.drop_table('invoices_customers')
    op.drop_column('invoices', 'signed_xml')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('signed_xml', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_table('invoices_customers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('vat_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('country_code', sa.VARCHAR(length=5), server_default=sa.text("'SA'::character varying"), autoincrement=False, nullable=True),
    sa.Column('street', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('building_number', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('division', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('postal_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('party_identification_scheme', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('party_identification_value', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('registration_name', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name='invoices_customers_invoice_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='invoices_customers_pkey')
    )
    op.create_index('ix_invoices_customers_id', 'invoices_customers', ['id'], unique=False)
    op.drop_index(op.f('ix_customer_snapshots_id'), table_name='customer_snapshots')
    op.drop_table('customer_snapshots')
    # ### end Alembic commands ###
