"""update sale invoices

Revision ID: 07378d4d31d0
Revises: a7d2d64a9051
Create Date: 2026-01-12 00:51:24.977303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07378d4d31d0'
down_revision: Union[str, None] = 'a7d2d64a9051'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sale_invoices', 'payment_means_code',
               existing_type=postgresql.ENUM('CASH', 'CHEQUE', 'CREDIT_TRANSFER', 'DEBIT_TRANSFER', 'PAYMENT_TO_BANK_ACCOUNT', 'BANK_CARD', name='paymentmeanscode'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('sale_invoices', 'original_invoice_id',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Integer(),
               existing_nullable=True, postgresql_using="original_invoice_id::integer")
    op.create_foreign_key(None, 'sale_invoices', 'sale_invoices', ['original_invoice_id'], ['id'])
    op.add_column('zatca_phase2_sale_invoice_data', sa.Column('status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zatca_phase2_sale_invoice_data', 'status')
    op.drop_constraint(None, 'sale_invoices', type_='foreignkey')
    op.alter_column('sale_invoices', 'original_invoice_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
    op.alter_column('sale_invoices', 'payment_means_code',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('CASH', 'CHEQUE', 'CREDIT_TRANSFER', 'DEBIT_TRANSFER', 'PAYMENT_TO_BANK_ACCOUNT', 'BANK_CARD', name='paymentmeanscode'),
               existing_nullable=False)
    # ### end Alembic commands ###
