"""updated branches

Revision ID: 210dc9d9340b
Revises: bbd3b6d9eea5
Create Date: 2026-01-05 16:27:49.297664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '210dc9d9340b'
down_revision: Union[str, None] = 'bbd3b6d9eea5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branches', sa.Column('tax_integration_status', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('branches', 'tax_integration_status')
    # ### end Alembic commands ###
