"""updated zatca tables

Revision ID: 237a3cd75f5a
Revises: 210dc9d9340b
Create Date: 2026-01-05 17:35:17.321346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '237a3cd75f5a'
down_revision: Union[str, None] = '210dc9d9340b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sale_invoices_original_invoice_id_fkey', 'sale_invoices', type_='foreignkey')
    op.alter_column('sale_invoices', 'original_invoice_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=30),
               existing_nullable=True)
    op.add_column('zatca_phase2_branches_data', sa.Column('tax_authority', sa.String(length=50), nullable=True))
    op.add_column('zatca_phase2_sale_invoice_data', sa.Column('tax_authority', sa.String(length=50), nullable=True))
    op.add_column('zatca_phase2_sale_invoice_lines_data', sa.Column('tax_authority', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zatca_phase2_sale_invoice_lines_data', 'tax_authority')
    op.drop_column('zatca_phase2_sale_invoice_data', 'tax_authority')
    op.drop_column('zatca_phase2_branches_data', 'tax_authority')
    op.create_foreign_key('sale_invoices_original_invoice_id_fkey', 'sale_invoices', 'sale_invoices', ['original_invoice_id'], ['id'])
    op.alter_column('sale_invoices', 'original_invoice_id',
               existing_type=sa.String(length=30),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
