"""updated user model

Revision ID: 25ae7fa10823
Revises: 336ed1a062f9
Create Date: 2025-07-14 15:02:22.975573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25ae7fa10823'
down_revision: Union[str, None] = '336ed1a062f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('organization_name', sa.String(length=250), nullable=True))
    op.drop_column('users', 'unit_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('unit_name', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.drop_column('users', 'organization_name')
    # ### end Alembic commands ###
