"""update buy invoices

Revision ID: 3ba82a43966e
Revises: c14464effc21
Create Date: 2025-11-29 19:45:39.664221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ba82a43966e'
down_revision: Union[str, None] = 'c14464effc21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buy_invoices', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.add_column('buy_invoices', sa.Column('branch_id', sa.Integer(), nullable=True))
    op.drop_constraint('buy_invoices_user_id_fkey', 'buy_invoices', type_='foreignkey')
    op.create_foreign_key(None, 'buy_invoices', 'branches', ['branch_id'], ['id'])
    op.create_foreign_key(None, 'buy_invoices', 'organizations', ['organization_id'], ['id'])
    op.drop_column('buy_invoices', 'user_id')
    op.drop_column('buy_invoices_lines', 'tax_exemption_reason')
    op.drop_column('buy_invoices_lines', 'tax_exemption_reason_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buy_invoices_lines', sa.Column('tax_exemption_reason_code', postgresql.ENUM('VATEX_SA_29', 'VATEX_SA_29_7', 'VATEX_SA_30', 'VATEX_SA_32', 'VATEX_SA_33', 'VATEX_SA_34_1', 'VATEX_SA_34_2', 'VATEX_SA_34_3', 'VATEX_SA_34_4', 'VATEX_SA_34_5', 'VATEX_SA_35', 'VATEX_SA_36', 'VATEX_SA_EDU', 'VATEX_SA_HEA', 'VATEX_SA_MLTRY', 'VATEX-SA-OOS', 'VATEX_SA_OOS', name='taxexemptionreasoncode'), autoincrement=False, nullable=True))
    op.add_column('buy_invoices_lines', sa.Column('tax_exemption_reason', sa.VARCHAR(length=4000), autoincrement=False, nullable=True))
    op.add_column('buy_invoices', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'buy_invoices', type_='foreignkey')
    op.drop_constraint(None, 'buy_invoices', type_='foreignkey')
    op.create_foreign_key('buy_invoices_user_id_fkey', 'buy_invoices', 'users', ['user_id'], ['id'])
    op.drop_column('buy_invoices', 'branch_id')
    op.drop_column('buy_invoices', 'organization_id')
    # ### end Alembic commands ###
