"""updated zatca models

Revision ID: 3cd31e354ec0
Revises: 07378d4d31d0
Create Date: 2026-01-12 01:36:20.957226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cd31e354ec0'
down_revision: Union[str, None] = '07378d4d31d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('zatca_phase2_sale_invoice_data', 'response',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True, postgresql_using="response::json")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('zatca_phase2_sale_invoice_data', 'response',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
