"""removed icv from buy invoices

Revision ID: 3e0b35cb7391
Revises: 861c822b3c81
Create Date: 2025-10-11 03:52:34.443270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e0b35cb7391'
down_revision: Union[str, None] = '861c822b3c81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buy_invoices', 'icv')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buy_invoices', sa.Column('icv', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
