"""updated customers and suppliers

Revision ID: 3edef7fc2021
Revises: 1cb6f8b1a65f
Create Date: 2025-10-04 22:45:18.331044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3edef7fc2021'
down_revision: Union[str, None] = '1cb6f8b1a65f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('bank_account', sa.String(length=100), nullable=True))
    op.add_column('customers', sa.Column('website', sa.String(length=100), nullable=True))
    op.add_column('customers', sa.Column('notes', sa.String(length=1000), nullable=True))
    op.add_column('suppliers', sa.Column('bank_account', sa.String(length=100), nullable=True))
    op.add_column('suppliers', sa.Column('website', sa.String(length=100), nullable=True))
    op.add_column('suppliers', sa.Column('notes', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'notes')
    op.drop_column('suppliers', 'website')
    op.drop_column('suppliers', 'bank_account')
    op.drop_column('customers', 'notes')
    op.drop_column('customers', 'website')
    op.drop_column('customers', 'bank_account')
    # ### end Alembic commands ###
