"""bug fix

Revision ID: 4166b1cd4a61
Revises: 61388d151a24
Create Date: 2026-01-16 03:01:24.180913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4166b1cd4a61'
down_revision: Union[str, None] = '61388d151a24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_permission_resource_action', 'permissions', ['resource', 'action'])
    op.create_unique_constraint('unique_user_permission', 'user_permissions', ['user_id', 'permission_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_permission', 'user_permissions', type_='unique')
    op.drop_constraint('unique_permission_resource_action', 'permissions', type_='unique')
    # ### end Alembic commands ###
