"""updated csid

Revision ID: 41c76159acbd
Revises: a7c8df7608cb
Create Date: 2025-07-20 15:58:49.174259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41c76159acbd'
down_revision: Union[str, None] = 'a7c8df7608cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('csids', sa.Column('disposition_message', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('csids', 'disposition_message')
    # ### end Alembic commands ###
