"""update:sale invoices:added invoice number and other metadata

Revision ID: 4a105794f3af
Revises: 8c0364c7deaf
Create Date: 2025-10-21 06:05:52.618632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a105794f3af'
down_revision: Union[str, None] = '8c0364c7deaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale_invoices', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('sale_invoices', sa.Column('seq_number', sa.Integer(), nullable=True))
    op.add_column('sale_invoices', sa.Column('invoice_number', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_sale_invoices_invoice_number'), 'sale_invoices', ['invoice_number'], unique=False)
    op.create_index(op.f('ix_sale_invoices_year'), 'sale_invoices', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sale_invoices_year'), table_name='sale_invoices')
    op.drop_index(op.f('ix_sale_invoices_invoice_number'), table_name='sale_invoices')
    op.alter_column('sale_invoices', 'prices_include_tax',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_column('sale_invoices', 'invoice_number')
    op.drop_column('sale_invoices', 'seq_number')
    op.drop_column('sale_invoices', 'year')
    # ### end Alembic commands ###
