"""added organizations - branches

Revision ID: 50d14488295f
Revises: 646375c60659
Create Date: 2025-11-09 03:04:43.042468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50d14488295f'
down_revision: Union[str, None] = '646375c60659'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('country_code', sa.String(length=30), nullable=True),
    sa.Column('vat_number', sa.String(length=20), nullable=True),
    sa.Column('business_category', sa.String(length=100), nullable=True),
    sa.Column('tax_scheme', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('street', sa.String(length=300), nullable=True),
    sa.Column('building_number', sa.String(length=15), nullable=True),
    sa.Column('division', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('address', sa.String(length=400), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_table('branches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('is_main_branch', sa.BOOLEAN(), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('street', sa.String(length=300), nullable=True),
    sa.Column('building_number', sa.String(length=15), nullable=True),
    sa.Column('division', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('address', sa.String(length=400), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branches_id'), 'branches', ['id'], unique=False)
    op.add_column('users', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'users', 'organizations', ['organization_id'], ['id'])
    op.drop_column('users', 'organization_unit_name')
    op.drop_column('users', 'invoicing_type')
    op.drop_column('users', 'business_category')
    op.drop_column('users', 'party_identification_value')
    op.drop_column('users', 'organization_name')
    op.drop_column('users', 'country_code')
    op.drop_column('users', 'postal_code')
    op.drop_column('users', 'stage')
    op.drop_column('users', 'address')
    op.drop_column('users', 'common_name')
    op.drop_column('users', 'city')
    op.drop_column('users', 'division')
    op.drop_column('users', 'registration_name')
    op.drop_column('users', 'vat_number')
    op.drop_column('users', 'party_identification_scheme')
    op.drop_column('users', 'building_number')
    op.drop_column('users', 'street')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('street', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('building_number', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('party_identification_scheme', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('vat_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('registration_name', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('division', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('city', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('common_name', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('address', sa.VARCHAR(length=400), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('stage', postgresql.ENUM('PRODUCTION', 'COMPLIANCE', name='stage'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('postal_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('country_code', sa.VARCHAR(length=5), server_default=sa.text("'SA'::character varying"), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('organization_name', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('party_identification_value', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('business_category', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('invoicing_type', sa.VARCHAR(length=5), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('organization_unit_name', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'name')
    op.drop_column('users', 'organization_id')
    op.drop_index(op.f('ix_branches_id'), table_name='branches')
    op.drop_table('branches')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
