"""updated sale invoices

Revision ID: 51cade6f861e
Revises: 6f7e05aa6382
Create Date: 2025-12-11 05:01:33.997815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51cade6f861e'
down_revision: Union[str, None] = '6f7e05aa6382'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TABLE sale_invoices
        ALTER COLUMN issue_time TYPE time
        USING issue_time::time without time zone;
    """)
    op.alter_column('zatca_branches_metadata', 'stage',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('zatca_branches_metadata', 'stage',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('sale_invoices', 'issue_time',
               existing_type=sa.Time(),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)
    # ### end Alembic commands ###
