"""updated invoices

Revision ID: 567f3b59cd2b
Revises: 2f2c271a0a0b
Create Date: 2025-08-02 22:18:26.116745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '567f3b59cd2b'
down_revision: Union[str, None] = '2f2c271a0a0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('signed_xml', sa.Text(), nullable=True))
    op.add_column('invoices', sa.Column('signed_xml_base64', sa.Text(), nullable=True))
    op.add_column('invoices', sa.Column('invoice_hash', sa.Text(), nullable=True))
    op.add_column('invoices', sa.Column('uuid', sa.UUID(), nullable=True))
    op.add_column('invoices', sa.Column('icv', sa.Integer(), nullable=False))
    op.add_column('invoices', sa.Column('pih', sa.Text(), nullable=False))
    op.add_column('invoices', sa.Column('base64_qr_code', sa.Text(), nullable=True))
    op.drop_column('invoices', 'xml_invoice')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('xml_invoice', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('invoices', 'base64_qr_code')
    op.drop_column('invoices', 'pih')
    op.drop_column('invoices', 'icv')
    op.drop_column('invoices', 'uuid')
    op.drop_column('invoices', 'invoice_hash')
    op.drop_column('invoices', 'signed_xml_base64')
    op.drop_column('invoices', 'signed_xml')
    # ### end Alembic commands ###
