"""update:sale invoices:changed some field to nullable

Revision ID: 646375c60659
Revises: 879947980f83
Create Date: 2025-11-05 04:24:16.151875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '646375c60659'
down_revision: Union[str, None] = '879947980f83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sale_invoices', 'icv',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sale_invoices', 'pih',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sale_invoices', 'pih',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('sale_invoices', 'icv',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
