"""updated invoices

Revision ID: 6af2c0cdfc63
Revises: a6c18edbb161
Create Date: 2025-08-06 21:08:34.063067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6af2c0cdfc63'
down_revision: Union[str, None] = 'a6c18edbb161'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('tax_exemption_reason_code', sa.Enum('VATEX_SA_29', 'VATEX_SA_29_7', 'VATEX_SA_30', 'VATEX_SA_32', 'VATEX_SA_33', 'VATEX_SA_34_1', 'VATEX_SA_34_2', 'VATEX_SA_34_3', 'VATEX_SA_34_4', 'VATEX_SA_34_5', 'VATEX_SA_35', 'VATEX_SA_36', 'VATEX_SA_EDU', 'VATEX_SA_HEA', 'VATEX_SA_MLTRY', name='taxexemptionreasoncode'), nullable=True))
    op.add_column('invoices', sa.Column('tax_exemption_reason', sa.String(length=4000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'tax_exemption_reason')
    op.drop_column('invoices', 'tax_exemption_reason_code')
    # ### end Alembic commands ###
