"""updated invoices

Revision ID: 6c2817e777fc
Revises: 6af2c0cdfc63
Create Date: 2025-08-07 00:38:06.277272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c2817e777fc'
down_revision: Union[str, None] = '6af2c0cdfc63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('registration_name', sa.String(length=250), nullable=True))
    op.drop_column('customers', 'registraion_name')
    op.alter_column('invoices', 'invoice_type',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('STANDARD', 'SIMPLIFIED', name='invoicetype'),
               existing_nullable=False)
    op.add_column('invoices_customers', sa.Column('registration_name', sa.String(length=250), nullable=False))
    op.drop_column('invoices_customers', 'registraion_name')
    op.add_column('users', sa.Column('registration_name', sa.String(length=250), nullable=True))
    op.drop_column('users', 'registraion_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('registraion_name', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.drop_column('users', 'registration_name')
    op.add_column('invoices_customers', sa.Column('registraion_name', sa.VARCHAR(length=250), autoincrement=False, nullable=False))
    op.drop_column('invoices_customers', 'registration_name')
    op.alter_column('invoices', 'invoice_type',
               existing_type=sa.Enum('STANDARD', 'SIMPLIFIED', name='invoicetype'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.add_column('customers', sa.Column('registraion_name', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.drop_column('customers', 'registration_name')
    # ### end Alembic commands ###
