"""sale ivoices fix

Revision ID: 6f7e05aa6382
Revises: b274d3d305f1
Create Date: 2025-12-11 04:23:36.221661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f7e05aa6382'
down_revision: Union[str, None] = 'b274d3d305f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale_invoices', sa.Column('completed_tax_scheme', sa.BOOLEAN(), nullable=True))
    op.add_column('users', sa.Column('branch_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'branches', ['branch_id'], ['id'])
    op.add_column('zatca_csids', sa.Column('stage', sa.String(length=50), nullable=True))
    op.drop_column('zatca_csids', 'type')
    op.add_column('zatca_sale_invoice_lines_metadata', sa.Column('invoice_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'zatca_sale_invoice_lines_metadata', 'sale_invoices', ['invoice_id'], ['id'])
    op.alter_column('zatca_sale_invoice_metadata', 'status_code',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('zatca_sale_invoice_metadata', 'status_code',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_constraint(None, 'zatca_sale_invoice_lines_metadata', type_='foreignkey')
    op.drop_column('zatca_sale_invoice_lines_metadata', 'invoice_id')
    op.add_column('zatca_csids', sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('zatca_csids', 'stage')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'branch_id')
    op.drop_column('sale_invoices', 'completed_tax_scheme')
    # ### end Alembic commands ###
