"""added pos in sale invoices

Revision ID: 74aaa34f2a5d
Revises: c8e691fcc7ae
Create Date: 2026-01-13 00:37:34.834955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74aaa34f2a5d'
down_revision: Union[str, None] = 'c8e691fcc7ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale_invoices', sa.Column('point_of_sale_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sale_invoices', 'points_of_sale', ['point_of_sale_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sale_invoices', type_='foreignkey')
    op.drop_column('sale_invoices', 'point_of_sale_id')
    # ### end Alembic commands ###
