"""refactoring

Revision ID: 7990763b0fd7
Revises: 237a3cd75f5a
Create Date: 2026-01-07 23:01:23.325330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7990763b0fd7'
down_revision: Union[str, None] = '237a3cd75f5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buy_invoices', sa.Column('prices_include_tax', sa.BOOLEAN(), nullable=True))
    op.drop_column('buy_invoices_lines', 'price_includes_tax')
    op.add_column('customers', sa.Column('whatsapp', sa.String(length=20), nullable=True))
    op.add_column('customers', sa.Column('email', sa.String(length=50), nullable=True))
    op.add_column('suppliers', sa.Column('whatsapp', sa.String(length=20), nullable=True))
    op.add_column('suppliers', sa.Column('email', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'email')
    op.drop_column('suppliers', 'whatsapp')
    op.drop_column('customers', 'email')
    op.drop_column('customers', 'whatsapp')
    op.add_column('buy_invoices_lines', sa.Column('price_includes_tax', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('buy_invoices', 'prices_include_tax')
    # ### end Alembic commands ###
