"""updated buy invoices

Revision ID: 861c822b3c81
Revises: c330bb617f1b
Create Date: 2025-10-10 20:33:30.389336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '861c822b3c81'
down_revision: Union[str, None] = 'c330bb617f1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buy_invoices_lines', sa.Column('price_discount', sa.DECIMAL(scale=2), nullable=True))
    op.alter_column('items', 'default_sale_price',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('items', 'default_buy_price',
               existing_type=sa.NUMERIC(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'default_buy_price',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('items', 'default_sale_price',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.drop_column('buy_invoices_lines', 'price_discount')
    # ### end Alembic commands ###
