"""update:sale invoices: added quotations

Revision ID: 879947980f83
Revises: 4a105794f3af
Create Date: 2025-10-28 04:59:08.249857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '879947980f83'
down_revision: Union[str, None] = '4a105794f3af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale_invoices', sa.Column('document_type', sa.Enum('INVOICE', 'QUOTATION', name='documenttype', native_enum=False), nullable=True))
    op.add_column('sale_invoices', sa.Column('is_locked', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sale_invoices', 'is_locked')
    op.drop_column('sale_invoices', 'document_type')
    # ### end Alembic commands ###
