"""update:sale invoices:moved price include tax to invoice level

Revision ID: 8c0364c7deaf
Revises: 5d25eae17f22
Create Date: 2025-10-19 04:59:13.334615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c0364c7deaf'
down_revision: Union[str, None] = '5d25eae17f22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale_invoices', sa.Column('prices_include_tax', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sale_invoices', 'prices_include_tax')
    # ### end Alembic commands ###
