"""updated invoices

Revision ID: a6c18edbb161
Revises: 567f3b59cd2b
Create Date: 2025-08-02 23:32:53.134230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6c18edbb161'
down_revision: Union[str, None] = '567f3b59cd2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices_lines', sa.Column('item_unit_code', sa.String(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices_lines', 'item_unit_code')
    # ### end Alembic commands ###
