"""added csid

Revision ID: a7c8df7608cb
Revises: 1f9db2c274a9
Create Date: 2025-07-20 04:14:26.808401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7c8df7608cb'
down_revision: Union[str, None] = '1f9db2c274a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('csids',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Enum('PRODUCTION', 'COMPLIANCE', name='csidtype'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('private_key', sa.String(), nullable=False),
    sa.Column('csr_base64', sa.String(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('binary_security_token', sa.String(), nullable=False),
    sa.Column('secret', sa.String(), nullable=False),
    sa.Column('certificate', sa.String(), nullable=False),
    sa.Column('authorization', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_csids_id'), 'csids', ['id'], unique=False)
    op.add_column('users', sa.Column('is_completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_completed')
    op.drop_index(op.f('ix_csids_id'), table_name='csids')
    op.drop_table('csids')
    # ### end Alembic commands ###
