"""updated sale invoices

Revision ID: a7d2d64a9051
Revises: 7990763b0fd7
Create Date: 2026-01-09 23:17:16.027612

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7d2d64a9051'
down_revision: Union[str, None] = '7990763b0fd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale_invoices', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('sale_invoices', sa.Column('tax_authority_status', sa.String(length=50), nullable=True))
    op.drop_column('sale_invoices', 'completed_tax_integration')
    op.drop_column('sale_invoices', 'is_locked')
    op.drop_constraint('zatca_phase2_sale_invoice_data_invoice_id_fkey', 'zatca_phase2_sale_invoice_data', type_='foreignkey')
    op.create_foreign_key(None, 'zatca_phase2_sale_invoice_data', 'sale_invoices', ['invoice_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('zatca_phase2_sale_invoice_lines_data_invoice_line_id_fkey', 'zatca_phase2_sale_invoice_lines_data', type_='foreignkey')
    op.drop_constraint('zatca_phase2_sale_invoice_lines_data_invoice_id_fkey', 'zatca_phase2_sale_invoice_lines_data', type_='foreignkey')
    op.create_foreign_key(None, 'zatca_phase2_sale_invoice_lines_data', 'sale_invoices_lines', ['invoice_line_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'zatca_phase2_sale_invoice_lines_data', 'sale_invoices', ['invoice_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'zatca_phase2_sale_invoice_lines_data', type_='foreignkey')
    op.drop_constraint(None, 'zatca_phase2_sale_invoice_lines_data', type_='foreignkey')
    op.create_foreign_key('zatca_phase2_sale_invoice_lines_data_invoice_id_fkey', 'zatca_phase2_sale_invoice_lines_data', 'sale_invoices', ['invoice_id'], ['id'])
    op.create_foreign_key('zatca_phase2_sale_invoice_lines_data_invoice_line_id_fkey', 'zatca_phase2_sale_invoice_lines_data', 'sale_invoices_lines', ['invoice_line_id'], ['id'])
    op.drop_constraint(None, 'zatca_phase2_sale_invoice_data', type_='foreignkey')
    op.create_foreign_key('zatca_phase2_sale_invoice_data_invoice_id_fkey', 'zatca_phase2_sale_invoice_data', 'sale_invoices', ['invoice_id'], ['id'])
    op.add_column('sale_invoices', sa.Column('is_locked', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('sale_invoices', sa.Column('completed_tax_integration', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('sale_invoices', 'tax_authority_status')
    op.drop_column('sale_invoices', 'status')
    # ### end Alembic commands ###
