"""created branch metadata

Revision ID: b274d3d305f1
Revises: 3ba82a43966e
Create Date: 2025-12-08 05:01:45.455805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b274d3d305f1'
down_revision: Union[str, None] = '3ba82a43966e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zatca_branches_metadata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('icv', sa.Integer(), nullable=True),
    sa.Column('pih', sa.Text(), nullable=True),
    sa.Column('country_code', sa.String(length=50), nullable=False),
    sa.Column('registration_name', sa.String(length=250), nullable=True),
    sa.Column('common_name', sa.String(length=250), nullable=True),
    sa.Column('organization_unit_name', sa.String(length=250), nullable=True),
    sa.Column('organization_name', sa.String(length=250), nullable=True),
    sa.Column('vat_number', sa.String(length=20), nullable=True),
    sa.Column('invoicing_type', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=400), nullable=True),
    sa.Column('business_category', sa.String(length=100), nullable=True),
    sa.Column('street', sa.String(length=300), nullable=True),
    sa.Column('building_number', sa.String(length=15), nullable=True),
    sa.Column('division', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('party_identification_scheme', sa.String(length=10), nullable=True),
    sa.Column('party_identification_value', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zatca_branches_metadata_id'), 'zatca_branches_metadata', ['id'], unique=False)
    op.create_table('zatca_csids',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('private_key', sa.String(), nullable=False),
    sa.Column('csr_base64', sa.String(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('disposition_message', sa.String(), nullable=False),
    sa.Column('binary_security_token', sa.String(), nullable=False),
    sa.Column('secret', sa.String(), nullable=False),
    sa.Column('certificate', sa.String(), nullable=False),
    sa.Column('authorization', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zatca_csids_id'), 'zatca_csids', ['id'], unique=False)
    op.create_table('zatca_sale_invoice_metadata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('icv', sa.Integer(), nullable=True),
    sa.Column('signed_xml_base64', sa.Text(), nullable=True),
    sa.Column('invoice_hash', sa.Text(), nullable=True),
    sa.Column('pih', sa.Text(), nullable=True),
    sa.Column('base64_qr_code', sa.Text(), nullable=True),
    sa.Column('stage', sa.String(length=50), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('status_code', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['sale_invoices.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zatca_sale_invoice_metadata_id'), 'zatca_sale_invoice_metadata', ['id'], unique=False)
    op.create_table('zatca_sale_invoice_lines_metadata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_line_id', sa.Integer(), nullable=True),
    sa.Column('tax_exemption_reason_code', sa.String(length=100), nullable=True),
    sa.Column('tax_exemption_reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invoice_line_id'], ['sale_invoices_lines.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zatca_sale_invoice_lines_metadata_id'), 'zatca_sale_invoice_lines_metadata', ['id'], unique=False)
    op.drop_index('ix_csids_id', table_name='csids')
    op.drop_table('csids')
    op.add_column('branches', sa.Column('status', sa.String(length=100), server_default='PENDING', nullable=True))
    op.add_column('buy_invoices', sa.Column('seq_number', sa.Integer(), nullable=True))
    op.add_column('sale_invoices', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.add_column('sale_invoices', sa.Column('branch_id', sa.Integer(), nullable=True))
    op.drop_constraint('sale_invoices_user_id_fkey', 'sale_invoices', type_='foreignkey')
    op.create_foreign_key(None, 'sale_invoices', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(None, 'sale_invoices', 'users', ['branch_id'], ['id'])
    op.drop_column('sale_invoices', 'signed_xml_base64')
    op.drop_column('sale_invoices', 'status_code')
    op.drop_column('sale_invoices', 'base64_qr_code')
    op.drop_column('sale_invoices', 'pih')
    op.drop_column('sale_invoices', 'icv')
    op.drop_column('sale_invoices', 'zatca_response')
    op.drop_column('sale_invoices', 'user_id')
    op.drop_column('sale_invoices', 'invoice_hash')
    op.drop_column('sale_invoices', 'stage')
    op.drop_column('sale_invoices_lines', 'tax_exemption_reason')
    op.drop_column('sale_invoices_lines', 'tax_exemption_reason_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale_invoices_lines', sa.Column('tax_exemption_reason_code', postgresql.ENUM('VATEX_SA_29', 'VATEX_SA_29_7', 'VATEX_SA_30', 'VATEX_SA_32', 'VATEX_SA_33', 'VATEX_SA_34_1', 'VATEX_SA_34_2', 'VATEX_SA_34_3', 'VATEX_SA_34_4', 'VATEX_SA_34_5', 'VATEX_SA_35', 'VATEX_SA_36', 'VATEX_SA_EDU', 'VATEX_SA_HEA', 'VATEX_SA_MLTRY', 'VATEX-SA-OOS', 'VATEX_SA_OOS', name='taxexemptionreasoncode'), autoincrement=False, nullable=True))
    op.add_column('sale_invoices_lines', sa.Column('tax_exemption_reason', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('sale_invoices', sa.Column('stage', postgresql.ENUM('PRODUCTION', 'COMPLIANCE', name='stage'), autoincrement=False, nullable=True))
    op.add_column('sale_invoices', sa.Column('invoice_hash', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('sale_invoices', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sale_invoices', sa.Column('zatca_response', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('sale_invoices', sa.Column('icv', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sale_invoices', sa.Column('pih', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('sale_invoices', sa.Column('base64_qr_code', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('sale_invoices', sa.Column('status_code', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('sale_invoices', sa.Column('signed_xml_base64', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint('sale_invoices_organization_id_fkey', 'sale_invoices', type_='foreignkey')
    op.drop_constraint('sale_invoices_branch_id_fkey', 'sale_invoices', type_='foreignkey')
    op.create_foreign_key('sale_invoices_user_id_fkey', 'sale_invoices', 'users', ['user_id'], ['id'])
    op.drop_column('sale_invoices', 'branch_id')
    op.drop_column('sale_invoices', 'organization_id')
    op.drop_column('buy_invoices', 'seq_number')
    op.drop_column('branches', 'status')
    op.create_table('csids',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('private_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('csr_base64', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('request_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('binary_security_token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('secret', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('certificate', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('authorization', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('disposition_message', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='csids_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='csids_pkey')
    )
    op.create_index('ix_csids_id', 'csids', ['id'], unique=False)
    op.drop_index(op.f('ix_zatca_sale_invoice_lines_metadata_id'), table_name='zatca_sale_invoice_lines_metadata')
    op.drop_table('zatca_sale_invoice_lines_metadata')
    op.drop_index(op.f('ix_zatca_sale_invoice_metadata_id'), table_name='zatca_sale_invoice_metadata')
    op.drop_table('zatca_sale_invoice_metadata')
    op.drop_index(op.f('ix_zatca_csids_id'), table_name='zatca_csids')
    op.drop_table('zatca_csids')
    op.drop_index(op.f('ix_zatca_branches_metadata_id'), table_name='zatca_branches_metadata')
    op.drop_table('zatca_branches_metadata')
    # ### end Alembic commands ###
