"""tax authority

Revision ID: bbd3b6d9eea5
Revises: 51cade6f861e
Create Date: 2026-01-02 19:20:32.270971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bbd3b6d9eea5'
down_revision: Union[str, None] = '51cade6f861e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zatca_phase2_branches_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('icv', sa.Integer(), nullable=True),
    sa.Column('pih', sa.Text(), nullable=True),
    sa.Column('country_code', sa.String(length=50), nullable=False),
    sa.Column('registration_name', sa.String(length=250), nullable=True),
    sa.Column('common_name', sa.String(length=250), nullable=True),
    sa.Column('organization_unit_name', sa.String(length=250), nullable=True),
    sa.Column('organization_name', sa.String(length=250), nullable=True),
    sa.Column('vat_number', sa.String(length=20), nullable=True),
    sa.Column('invoicing_type', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=400), nullable=True),
    sa.Column('business_category', sa.String(length=100), nullable=True),
    sa.Column('street', sa.String(length=300), nullable=True),
    sa.Column('building_number', sa.String(length=15), nullable=True),
    sa.Column('division', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('postal_code', sa.String(length=10), nullable=True),
    sa.Column('party_identification_scheme', sa.String(length=10), nullable=True),
    sa.Column('party_identification_value', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zatca_phase2_branches_data_id'), 'zatca_phase2_branches_data', ['id'], unique=False)
    op.create_table('zatca_phase2_csids',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('private_key', sa.String(), nullable=False),
    sa.Column('csr_base64', sa.String(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('disposition_message', sa.String(), nullable=False),
    sa.Column('binary_security_token', sa.String(), nullable=False),
    sa.Column('secret', sa.String(), nullable=False),
    sa.Column('certificate', sa.String(), nullable=False),
    sa.Column('authorization', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zatca_phase2_csids_id'), 'zatca_phase2_csids', ['id'], unique=False)
    op.create_table('zatca_phase2_sale_invoice_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('icv', sa.Integer(), nullable=True),
    sa.Column('signed_xml_base64', sa.Text(), nullable=True),
    sa.Column('invoice_hash', sa.Text(), nullable=True),
    sa.Column('pih', sa.Text(), nullable=True),
    sa.Column('base64_qr_code', sa.Text(), nullable=True),
    sa.Column('stage', sa.String(length=50), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['sale_invoices.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zatca_phase2_sale_invoice_data_id'), 'zatca_phase2_sale_invoice_data', ['id'], unique=False)
    op.create_table('zatca_phase2_sale_invoice_lines_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('invoice_line_id', sa.Integer(), nullable=True),
    sa.Column('tax_exemption_reason_code', sa.String(length=100), nullable=True),
    sa.Column('tax_exemption_reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['sale_invoices.id'], ),
    sa.ForeignKeyConstraint(['invoice_line_id'], ['sale_invoices_lines.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zatca_phase2_sale_invoice_lines_data_id'), 'zatca_phase2_sale_invoice_lines_data', ['id'], unique=False)
    op.drop_index('ix_zatca_sale_invoice_metadata_id', table_name='zatca_sale_invoice_metadata')
    op.drop_table('zatca_sale_invoice_metadata')
    op.drop_index('ix_zatca_branches_metadata_id', table_name='zatca_branches_metadata')
    op.drop_table('zatca_branches_metadata')
    op.drop_index('ix_zatca_csids_id', table_name='zatca_csids')
    op.drop_table('zatca_csids')
    op.drop_index('ix_zatca_sale_invoice_lines_metadata_id', table_name='zatca_sale_invoice_lines_metadata')
    op.drop_table('zatca_sale_invoice_lines_metadata')
    op.add_column('organizations', sa.Column('tax_authority', sa.String(length=50), nullable=True))
    op.drop_column('organizations', 'tax_scheme')
    op.add_column('sale_invoices', sa.Column('completed_tax_integration', sa.BOOLEAN(), nullable=True))
    op.drop_column('sale_invoices', 'completed_tax_scheme')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale_invoices', sa.Column('completed_tax_scheme', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('sale_invoices', 'completed_tax_integration')
    op.add_column('organizations', sa.Column('tax_scheme', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('organizations', 'tax_authority')
    op.create_table('zatca_sale_invoice_lines_metadata',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('invoice_line_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tax_exemption_reason_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('tax_exemption_reason', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('invoice_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='zatca_sale_invoice_lines_metadata_created_by_fkey'),
    sa.ForeignKeyConstraint(['invoice_id'], ['sale_invoices.id'], name='zatca_sale_invoice_lines_metadata_invoice_id_fkey'),
    sa.ForeignKeyConstraint(['invoice_line_id'], ['sale_invoices_lines.id'], name='zatca_sale_invoice_lines_metadata_invoice_line_id_fkey'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='zatca_sale_invoice_lines_metadata_updated_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='zatca_sale_invoice_lines_metadata_pkey')
    )
    op.create_index('ix_zatca_sale_invoice_lines_metadata_id', 'zatca_sale_invoice_lines_metadata', ['id'], unique=False)
    op.create_table('zatca_csids',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('branch_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('private_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('csr_base64', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('request_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('disposition_message', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('binary_security_token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('secret', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('certificate', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('authorization', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stage', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name='zatca_csids_branch_id_fkey'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='zatca_csids_created_by_fkey'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='zatca_csids_organization_id_fkey'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='zatca_csids_updated_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='zatca_csids_pkey')
    )
    op.create_index('ix_zatca_csids_id', 'zatca_csids', ['id'], unique=False)
    op.create_table('zatca_branches_metadata',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('branch_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stage', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('icv', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pih', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('country_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('registration_name', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('common_name', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('organization_unit_name', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('organization_name', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('vat_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('invoicing_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=400), autoincrement=False, nullable=True),
    sa.Column('business_category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('street', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('building_number', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('division', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('postal_code', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('party_identification_scheme', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('party_identification_value', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], name='zatca_branches_metadata_branch_id_fkey'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='zatca_branches_metadata_created_by_fkey'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name='zatca_branches_metadata_organization_id_fkey'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='zatca_branches_metadata_updated_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='zatca_branches_metadata_pkey')
    )
    op.create_index('ix_zatca_branches_metadata_id', 'zatca_branches_metadata', ['id'], unique=False)
    op.create_table('zatca_sale_invoice_metadata',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('icv', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('signed_xml_base64', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('invoice_hash', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('pih', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('base64_qr_code', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('stage', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('response', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status_code', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='zatca_sale_invoice_metadata_created_by_fkey'),
    sa.ForeignKeyConstraint(['invoice_id'], ['sale_invoices.id'], name='zatca_sale_invoice_metadata_invoice_id_fkey'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name='zatca_sale_invoice_metadata_updated_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='zatca_sale_invoice_metadata_pkey')
    )
    op.create_index('ix_zatca_sale_invoice_metadata_id', 'zatca_sale_invoice_metadata', ['id'], unique=False)
    op.drop_index(op.f('ix_zatca_phase2_sale_invoice_lines_data_id'), table_name='zatca_phase2_sale_invoice_lines_data')
    op.drop_table('zatca_phase2_sale_invoice_lines_data')
    op.drop_index(op.f('ix_zatca_phase2_sale_invoice_data_id'), table_name='zatca_phase2_sale_invoice_data')
    op.drop_table('zatca_phase2_sale_invoice_data')
    op.drop_index(op.f('ix_zatca_phase2_csids_id'), table_name='zatca_phase2_csids')
    op.drop_table('zatca_phase2_csids')
    op.drop_index(op.f('ix_zatca_phase2_branches_data_id'), table_name='zatca_phase2_branches_data')
    op.drop_table('zatca_phase2_branches_data')
    # ### end Alembic commands ###
