"""added org and branch fks

Revision ID: c14464effc21
Revises: f43cf891a9c4
Create Date: 2025-11-23 05:26:13.105815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c14464effc21'
down_revision: Union[str, None] = 'f43cf891a9c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('branch_id', sa.Integer(), nullable=True))
    op.add_column('customers', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.drop_constraint('customers_user_id_fkey', 'customers', type_='foreignkey')
    op.create_foreign_key(None, 'customers', 'branches', ['branch_id'], ['id'])
    op.create_foreign_key(None, 'customers', 'organizations', ['organization_id'], ['id'])
    op.drop_column('customers', 'user_id')
    op.add_column('items', sa.Column('branch_id', sa.Integer(), nullable=True))
    op.add_column('items', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.drop_constraint('items_user_id_fkey', 'items', type_='foreignkey')
    op.create_foreign_key(None, 'items', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(None, 'items', 'branches', ['branch_id'], ['id'])
    op.drop_column('items', 'user_id')
    op.add_column('suppliers', sa.Column('branch_id', sa.Integer(), nullable=True))
    op.add_column('suppliers', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.drop_constraint('suppliers_user_id_fkey', 'suppliers', type_='foreignkey')
    op.create_foreign_key(None, 'suppliers', 'organizations', ['organization_id'], ['id'])
    op.create_foreign_key(None, 'suppliers', 'branches', ['branch_id'], ['id'])
    op.drop_column('suppliers', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'suppliers', type_='foreignkey')
    op.drop_constraint(None, 'suppliers', type_='foreignkey')
    op.create_foreign_key('suppliers_user_id_fkey', 'suppliers', 'users', ['user_id'], ['id'])
    op.drop_column('suppliers', 'organization_id')
    op.drop_column('suppliers', 'branch_id')
    op.add_column('items', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.create_foreign_key('items_user_id_fkey', 'items', 'users', ['user_id'], ['id'])
    op.drop_column('items', 'organization_id')
    op.drop_column('items', 'branch_id')
    op.add_column('customers', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.create_foreign_key('customers_user_id_fkey', 'customers', 'users', ['user_id'], ['id'])
    op.drop_column('customers', 'organization_id')
    op.drop_column('customers', 'branch_id')
    # ### end Alembic commands ###
