"""added multi branch

Revision ID: cf5f574a8a89
Revises: fbf2cfc6401f
Create Date: 2026-02-01 19:32:14.024321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf5f574a8a89'
down_revision: Union[str, None] = 'fbf2cfc6401f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_branches', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_branches', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.alter_column("users", "branch_id", new_column_name="default_branch_id")
    op.drop_constraint('users_branch_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'branches', ['default_branch_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("default_branch_id", "branch_id", new_column_name="branch_id")
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_branch_id_fkey', 'users', 'branches', ['branch_id'], ['id'])
    op.drop_constraint(None, 'user_branches', type_='foreignkey')
    op.drop_column('user_branches', 'organization_id')
    # ### end Alembic commands ###
