"""updated invoices

Revision ID: d1627b8add9a
Revises: 6c2817e777fc
Create Date: 2025-08-08 17:16:41.214640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1627b8add9a'
down_revision: Union[str, None] = '6c2817e777fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    stage = sa.Enum('PRODUCTION', 'COMPLIANCE', name='stage')
    stage.create(op.get_bind(), checkfirst=True)
    op.add_column('invoices', sa.Column('stage', stage, nullable=True))
    op.add_column('invoices', sa.Column('zatca_response', sa.Text(), nullable=True))
    op.add_column('invoices', sa.Column('status_code', sa.String(length=5), nullable=True))
    op.add_column('users', sa.Column('stage', stage, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'stage')
    op.drop_column('invoices', 'status_code')
    op.drop_column('invoices', 'zatca_response')
    op.drop_column('invoices', 'stage')
    # ### end Alembic commands ###
