"""updated users role

Revision ID: f43cf891a9c4
Revises: 0b485e6ffcae
Create Date: 2025-11-19 01:16:25.643517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f43cf891a9c4'
down_revision: Union[str, None] = '0b485e6ffcae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('CLIENT', 'ADMIN', 'SUPER_ADMIN', name='userrole'),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.String(),
               type_=postgresql.ENUM('CLIENT', 'ADMIN', 'SUPER_ADMIN', name='userrole'),
               existing_nullable=False)
    # ### end Alembic commands ###
