"""invoices updates

Revision ID: fbf2cfc6401f
Revises: d45c3a36c3c5
Create Date: 2026-01-24 03:42:51.106907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbf2cfc6401f'
down_revision: Union[str, None] = 'd45c3a36c3c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buy_invoices', sa.Column('is_debited', sa.BOOLEAN(), nullable=True))
    op.add_column('sale_invoices', sa.Column('is_credited', sa.BOOLEAN(), server_default=sa.text('false'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sale_invoices', 'is_credited')
    op.drop_column('buy_invoices', 'is_debited')
    # ### end Alembic commands ###
